# Generated by Django 5.0.3 on 2024-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apartament_object', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=1, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('bron', 'Бронь'), ('purchased', 'Куплено'), ('barter', 'Бартер'), ('instalment', 'Рассрочка'), ('cancel', 'Отмена'), ('active', 'Активно')], max_length=30)),
                ('price', models.IntegerField()),
                ('client', models.CharField(max_length=100)),
                ('status_apartment', models.DateTimeField()),
            ],
        ),
    ]
