# Generated by Django 5.0.3 on 2024-03-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectApartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект')),
            ],
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='КВ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='client',
            field=models.CharField(max_length=100, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('bron', 'Бронь'), ('purchased', 'Куплено'), ('barter', 'Бартер'), ('instalment', 'Рассрочка'), ('cancel', 'Отмена'), ('active', 'Активна')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status_apartment',
            field=models.DateTimeField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartament_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='apartament.objectapartament', verbose_name='Объект'),
        ),
    ]
