# Generated by Django 5.0.3 on 2024-03-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartament', '0002_objectapartament_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectapartament',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartament_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartament', to='apartament.objectapartament', verbose_name='Объект'),
        ),
    ]
