# Generated by Django 5.0.3 on 2024-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartament', '0003_alter_objectapartament_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='№ Квартиры'),
        ),
    ]
