# Generated by Django 5.0.3 on 2024-03-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartament', '0004_alter_apartment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='name',
            new_name='number_apartament',
        ),
    ]
