# Generated by Django 5.0.3 on 2024-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartament', '0005_rename_name_apartment_number_apartament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_apartament',
            field=models.IntegerField(verbose_name='№ Квартиры'),
        ),
    ]
